# This is the single dossier you need to edit with your specific settings.
# It is mounted read-only into all containers.

# Alpaca API configuration
alpaca:
  key: "YOUR_ALPACA_KEY" # Can be overridden by env var ALPACA_KEY
  secret: "YOUR_ALPACA_SECRET" # Can be overridden by env var ALPACA_SECRET
  base_url: "https://paper-api.alpaca.markets"

# Telegram Bot configuration
telegram:
  bot_token: "BOT_TOKEN_FROM_BOTFATHER" # Can be overridden by env var TELEGRAM_BOT_TOKEN
  chat_id: 123456789 # Can be overridden by env var TELEGRAM_CHAT_ID

# OpenAI API configuration
openai:
  api_key: "OPENAI_KEY" # Can be overridden by env var OPENAI_API_KEY
  model_planner: "gpt-4o-mini" # User requested "gpt-4o-mini-high", using available model name
  model_general: "gpt-4o"

# Weaviate Vector Store configuration
weaviate:
  url: "https://your-weaviate-cluster.weaviate.network" # Can be overridden by env var WEAVIATE_URL
  api_key: "WEAVIATE_KEY" # Can be overridden by env var WEAVIATE_API_KEY
  collection_name: "TradingMemories"

# Risk Management parameters
risk:
  max_notional_usd: 10000
  max_var_pct: 0.02 # Maximum 2% Value at Risk
  halt_key: "HALT" # Redis key to signal system-wide pause

# Optics: Data sources for the news/event agents
optics:
  rss_feeds:
    - "http://feeds.reuters.com/reuters/businessNews"
    - "https://rss.nytimes.com/services/xml/rss/nyt/Business.xml"
    - "https://www.wsj.com/xml/rss/3_7014.xml"
  # TODO: Add API details for CourtListener and CivicFeed if you have them
  courtlistener_api_key: "YOUR_COURTLISTENER_API_KEY"
  civicfeed_api_key: "YOUR_CIVICFEED_API_KEY"
