alpaca:
  key: "YOUR_ALPACA_KEY"
  secret: "YOUR_ALPACA_SECRET"
  base_url: "https://paper-api.alpaca.markets"

telegram:
  bot_token: "YOUR_BOT_TOKEN_FROM_BOTFATHER"
  chat_id: 123456789

openai:
  api_key: "YOUR_OPENAI_KEY"
  model_planner: "gpt-4o-mini-high"
  model_general: "gpt-4o"

weaviate:
  url: "https://your-weaviate-cluster.weaviate.network"
  api_key: "YOUR_WEAVIATE_API_KEY"
  collection_name: "TradingMemories"

risk:
  max_notional_usd: 10000
  max_var_pct: 0.02
  halt_key: "HALT"

optics:
  rss_feeds:
    - "http://feeds.reuters.com/reuters/businessNews"
    - "https://rss.nytimes.com/services/xml/rss/nyt/Business.xml"
    - "https://www.wsj.com/xml/rss/3_7014.xml"
  courtlistener_api_key: "YOUR_COURTLISTENER_API_KEY"
  civicfeed_api_key: "YOUR_CIVICFEED_API_KEY"
